<template>
    <main>

    	<!--? BIENVENIDOS -->
        <div class="section-bienvenidos">
            <div class="slider-height2 d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12 pt-4 mt-3 mb-3">
                            <h2 class="mb-4 pl-4">Exposición Comercial 2020</h2>
                           	<p class="pl-4">¡Bienvenido! Presione en cada stand para acceder al contenido de cada expositor.</p>
                           	<p class="pl-4">Presione en donde vea este símbolo para acceder a otras áreas del Congreso:</p>
                             <img src="~/assets/img/buttons/SPOT.png" width="px" class="float-left pl-4">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="alert alert-dark d-block d-sm-none text-center aviso-pantalla m-0" role="alert">
          <img src="~/assets/img/buttons/gira_pantalla.png" width="px" class="float-left p-3 m-3">
          <p class="text-left">En dispositivos moviles le recomendamos mantener la vista  horizontal de su pantalla.</p>
        </div>
        <!-- BIENVENIDOS END -->

        <div> 
            <!-- Image Map Generated by http://www.image-map.net/ -->
            <img src="~/assets/images/banner.jpg" usemap="#image-map"  width="100%;">

            <map name="image-map">
                <area target="_blank" alt="hola" title="hola" href="www.google.com" coords="674,380,751,363,734,432,702,409" shape="poly">
            </map>
        </div>

     </main>
</template>
<script>
  export default {
    name: "index",

    data() {
      return {
        contact: {
          type: null
        },
        disabled: false
      }
    },

    methods: {
      async sendContact() {
        this.disabled = true;

        if (this.contact.type === 'Proveedor') {
          this.contact.mail_to = 'jorge@srcongress.mx';
        } else if (this.contact.type === 'Profesor') {
          this.contact.mail_to = 'adriana.sanchez@srcongress.mx';
        } else {
          this.contact.mail_to = 'atencion@srcongress.mx';
        }

        try {
          await this.$axios.$post('/emails/contact', this.contact);

          this.$swal('¡Mensaje enviado correctamente!', 'En caso de ser necesario nos pondremos en contacto contigo a la brevedad.', 'success')
          this.disabled = false;
          this.contact = {
            type: null
          }
        } catch (e) {
          console.error(e);
          this.disabled = false;
          this.$swal('¡Error al enviar datos!', 'Por favor contacte directamente a contacto@mastologia.org.mx', 'error');
        }
      }
    }
  }
</script>

<style lang="scss" scoped>
    @import "assets/scss/color";

    .section-bienvenidos{
    	background: linear-gradient(to bottom, #2F447D, #5798B1);
    	height:auto;
    	h2 , p{
    		color:white;
    		font-weight:lighter;
    	}
    }
    .slider-height2{
    	height:auto;
    }
    .aviso-pantalla{
      background-color:#7D4199!important;
      padding:30px 10px 30px 10px;
      p{
        color:white;
      }
    }


    .contact-info {
        a {
            color: $theme-color;
        }
    }
</style>