<template>
  <main>
    <!--? BIENVENIDOS -->
    <div class="section-bienvenidos">
      <div class="slider-height2 d-flex align-items-center">
        <div class="container">
          <div class="row">
            <div class="col-xl-12 pt-4 mt-3 mb-3">
              <h2 class="mb-4 pl-4 font-weight-bold">
                BIENVENIDO AL CONGRESO VIRTUAL AMMOM 2021
              </h2>
              <div>
                <p class="pl-4 float-left">
                  Para ir a las diferentes secciones del congreso presione el
                  símbolo:
                </p>
                <img
                  src="~/assets/img/buttons/stand.png"
                  width="60px"
                  class="float-left pl-4"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div
      class="alert alert-dark d-block d-sm-none text-center aviso-pantalla m-0"
      role="alert"
    >
      <img
        src="~/assets/img/buttons/gira_pantalla.png"
        width="px"
        class="float-left p-3 m-3"
      />
      <p class="text-left">
        En dispositivos moviles le recomendamos mantener la vista horizontal de
        su pantalla.
      </p>
    </div>
    <!-- BIENVENIDOS END -->

    <div>
      <!-- Image Map Generated by http://www.image-map.net/ -->
      <div style="position: relative">
        <img id="main-image" src="~/assets/images/lobby.jpg" width="100%" />
        <a
          @click="$bvModal.show('uno')"
          class="rim-hotspot stand-button"
          style="width: 20.1%; height: 17.2%; left: 0.8%; top: 51.8%"
        ></a>
        <a
          href="/congreso-virtual/expo"
          class="rim-hotspot stand-button"
          style="width: 9.1%; height: 14.2%; left: 35%; top: 34.8%"
        ></a>
        <a
          href="/congreso-virtual/expo"
          class="rim-hotspot stand-button"
          style="width: 8.1%; height: 13.2%; left: 44.8%; top: 35.8%"
        ></a>
        <a
          href="/live/uno"
          class="rim-hotspot stand-button"
          style="width: 8.1%; height: 16.2%; left: 64.8%; top: 29.8%"
        ></a>
        <a
          href="/live/uno"
          class="rim-hotspot stand-button"
          style="width: 8.1%; height: 13.2%; left: 72.8%; top: 26.8%"
        ></a>
        <a
          @click="$bvModal.show('seis')"
          class="rim-hotspot stand-button"
          style="width: 17.1%; height: 24.2%; left: 81.8%; top: 31.8%"
        ></a>
      </div>
    </div>
    <b-modal id="uno" hide-footer>
      <div class="d-block text-center">
        <h2 class="text-center">ATENCIÓN DE DUDAS</h2>
        <p class="my-4 text-center">
          Si tienes dudas generales sobre respecto al congreso, <br />
          escríbenos y nos pondremos en contacto a través del correo <br />
          eléctronico que nos proporciones.
        </p>
        <help-modal type="doubts" />
      </div>
    </b-modal>
    <b-modal id="seis" hide-footer>
      <div class="d-block text-center">
        <iframe
          width="420"
          height="315"
          frameborder="0"
          src="https://player.vimeo.com/video/542848197"
        >
        </iframe>
      </div>
    </b-modal>
  </main>
</template>


<script>
import HelpModal from "../../components/HelpModal.vue";
export default {
  components: { HelpModal },
  name: "index",
  middleware: ["authenticated"],

  head() {
    return {
      // __dangerouslyDisableSanitizers: ["script"],
      script: [
        {
          id: "pixel-script-poptin",
          src: 'https://cdn.popt.in/pixel.js?id=9806b22c1e4e5',
          type: "text/javascript",
          async: true
        },
      ],
    };
  },
};
</script>

<style lang="scss" scoped>
@import "assets/scss/color";

.section-bienvenidos {
  background: linear-gradient(to bottom, #170284, #6717cd);
  height: auto;
  h2,
  p {
    color: white;
    font-weight: lighter;
  }
}
.slider-height2 {
  height: auto;
}
.aviso-pantalla {
  background-color: #7d4199 !important;
  padding: 30px 10px 30px 10px;
  p {
    color: white;
  }
}

.contact-info {
  a {
    color: $theme-color;
  }
}
</style>
