<template>
    <main>

    	<!--? BIENVENIDOS -->
        <div class="section-bienvenidos">
            <div class="slider-height2 d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12 pt-4 mt-3 mb-3">
                            <h2 class="mb-4 pl-4">Exposición Comercial 2020</h2>
                           	<p class="pl-4">¡Bienvenido! Presione en cada stand para acceder al contenido de cada expositor.</p>
                           	<p class="pl-4">Presione en donde vea este símbolo para acceder a otras áreas del Congreso:</p>
                             <img src="~/assets/img/buttons/SPOT.png" width="px" class="float-left pl-4">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="alert alert-dark d-block d-sm-none text-center aviso-pantalla m-0" role="alert">
          <img src="~/assets/img/buttons/gira_pantalla.png" width="px" class="float-left p-3 m-3">
          <p class="text-left">En dispositivos moviles le recomendamos mantener la vista  horizontal de su pantalla.</p>
        </div>
        <!-- BIENVENIDOS END -->

        <div>
            <!-- Image Map Generated by http://www.image-map.net/ -->
            <div style="position:relative"><img id="main-image" src="~/assets/images/banner.jpg" width="100%">
            <a href="/congreso-virtual/simposio" class="rim-hotspot" style="width:15.1%; height:23.9%; left:84.0%; top:51.5%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
            <a href="/congreso-virtual/live" class="rim-hotspot" style="width:14.8%; height:20.5%; left:1.2%; top:50.7%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
            <a href="/congreso-virtual/lilly" class="rim-hotspot" style="width:7.3%; height:6.4%; left:76.0%; top:36.3%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
            <a href="/congreso-virtual/m8" class="rim-hotspot" style="width:10.9%; height:6.6%; left:77.5%; top:27.7%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
            <a href="/congreso-virtual/medix" class="rim-hotspot" style="width:6.7%; height:9.7%; left:68.4%; top:25.6%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
            <a href="/congreso-virtual/amgen" class="rim-hotspot" style="width:7.5%; height:6.1%; left:26.0%; top:25.1%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
            <a href="/congreso-virtual/italmex" class="rim-hotspot" style="width:9.6%; height:5.3%; left:20.2%; top:34.7%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
            <a href="/congreso-virtual/sandox" class="rim-hotspot" style="width:12.8%; height:6.9%; left:12.7%; top:23.9%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
            <a href="/congreso-virtual/asofarma" class="rim-hotspot" style="width:7.1%; height:10.6%; left:11.4%; top:32.0%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a></div>
        </div>

     </main>
</template>
<script>
  export default {
    name: "index",
    middleware: ['authenticated'],
  }
</script>

<style lang="scss" scoped>
    @import "assets/scss/color";

    .section-bienvenidos{
    	background: linear-gradient(to bottom, #2F447D, #5798B1);
    	height:auto;
    	h2 , p{
    		color:white;
    		font-weight:lighter;
    	}
    }
    .slider-height2{
    	height:auto;
    }
    .aviso-pantalla{
      background-color:#7D4199!important;
      padding:30px 10px 30px 10px;
      p{
        color:white;
      }
    }


    .contact-info {
        a {
            color: $theme-color;
        }
    }
</style>
