<template>
  <main>
    <!--? BIENVENIDOS -->
    <div class="section-bienvenidos">
      <div class="slider-height2 d-flex align-items-center">
        <div class="container">
          <div class="row">
            <div class="col-xl-12 pt-4 mt-3 mb-3">
              <h2 class="mb-4 pl-4 font-weight-bold">EXPO VIRTUAL 2021</h2>
              <p class="pl-4 pt-2">¡Bienvenido!</p>
              <div>
                <p class="pl-4 float-left">
                  Presione sobre cada stand para acceder al contenido de cada
                  expositor en el símbolo
                </p>
                <img
                  src="~/assets/img/buttons/stand.png"
                  width="60px"
                  class="float-left pl-4"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div
      class="alert alert-dark d-block d-sm-none text-center aviso-pantalla m-0"
      role="alert"
    >
      <img
        src="~/assets/img/buttons/gira_pantalla.png"
        width="px"
        class="float-left p-3 m-3"
      />
      <p class="text-left">
        En dispositivos moviles le recomendamos mantener la vista horizontal de
        su pantalla.
      </p>
    </div>
    <!-- BIENVENIDOS END -->

    <div>
      <!-- Image Map Generated by http://www.image-map.net/ -->
      <div style="position: relative">
        <img id="main-image" src="~/assets/images/lobby.jpg" width="100%" />
        <a
          href="/congreso-virtual/ammom"
          class="rim-hotspot"
          style="
            width: 13.1%;
            height: 17.2%;
            left: 25.8%;
            top: 31.8%;
            position: absolute;
            cursor: pointer;
            display: block;
            z-index: 5;
            overflow: hidden;
          "
        ></a>
        <a
          href="/congreso-virtual/medix"
          class="rim-hotspot"
          style="
            width: 13.1%;
            height: 17.2%;
            left: 42.8%;
            top: 31.8%;
            position: absolute;
            cursor: pointer;
            display: block;
            z-index: 5;
            overflow: hidden;
          "
        ></a>
        <a
          href="/congreso-virtual/abbott"
          class="rim-hotspot"
          style="
            width: 13.1%;
            height: 17.2%;
            left: 59.8%;
            top: 31.8%;
            position: absolute;
            cursor: pointer;
            display: block;
            z-index: 5;
            overflow: hidden;
          "
        ></a>
        <a
          href="/congreso-virtual/asofarma"
          class="rim-hotspot"
          style="
            width: 13.1%;
            height: 18.6%;
            left: 25.6%;
            top: 52.8%;
            position: absolute;
            cursor: pointer;
            display: block;
            z-index: 5;
            overflow: hidden;
          "
        ></a>
        <a
          href="/congreso-virtual/liomont"
          class="rim-hotspot"
          style="
            width: 13.1%;
            height: 18.6%;
            left: 42.6%;
            top: 52.8%;
            position: absolute;
            cursor: pointer;
            display: block;
            z-index: 5;
            overflow: hidden;
          "
        ></a>
        <a
          href="/congreso-virtual/amgen"
          class="rim-hotspot"
          style="
            width: 13.1%;
            height: 18.6%;
            left: 59.6%;
            top: 52.8%;
            position: absolute;
            cursor: pointer;
            display: block;
            z-index: 5;
            overflow: hidden;
          "
        ></a>
      </div>
    </div>
    <b-modal id="uno" hide-footer>
      <div class="d-block text-center">
        <h2 class="p-4">Disponible a partir del 23 de Octubre.</h2>
      </div>
    </b-modal>
  </main>
</template>


<script>
export default {
  name: "index",
  middleware: ["authenticated"],
};
</script>

<style lang="scss" scoped>
@import "assets/scss/color";

.section-bienvenidos {
  background: linear-gradient(to bottom, #170284, #6717cd);
  height: auto;
  h2,
  p {
    color: white;
    font-weight: lighter;
  }
}
.slider-height2 {
  height: auto;
}
.aviso-pantalla {
  background-color: #7d4199 !important;
  padding: 30px 10px 30px 10px;
  p {
    color: white;
  }
}

.contact-info {
  a {
    color: $theme-color;
  }
}
</style>
