<template>
    <div>
        <orientation-alert-component />
        <!-- Image Map Generated by http://www.image-map.net/ -->
        <div class="overflow-auto">
            <img alt="STAND" src="~/assets/img/map/STAND_GRAL.png" usemap="#image_map">
        </div>

        <map name="image_map" id="image_map">
            <area alt="Stand One" title="Stand One" href="/map/one" coords="78,470 77,639 189,701 363,600 365,583 268,528 268,443 194,399 " shape="polygon">
            <area alt="Stand Two" title="Stand Two" href="/map/one" coords="310,346 441,269 459,280 460,366 482,351 511,322 549,307 552,397 620,436 620,447 402,573 266,494 268,476 302,453 " shape="polygon">
            <area alt="Stand Three" title="Stand Three" href="/map/one" coords="757,387 898,298 898,286 839,257 839,160 788,126 719,107 718,186 576,266 574,285 " shape="polygon">
            <area alt="Stand Four" title="Stand Four" href="/map/one" coords="784,404 978,518 1125,431 1122,353 1091,338 1082,309 1014,261 932,227 931,305 " shape="polygon">
            <area alt="Stand Five" title="Stand Five" href="/map/one" coords="1338,503 1333,423 1226,360 1200,372 1197,460 1161,440 1023,523 1019,544 1198,646 1352,551 1335,534 " shape="polygon">
        </map>
    </div>
</template>

<script>
  export default {
    name: "ImageMap",
  }
</script>

<style lang="scss" scoped>

</style>