<template>
    <div>

        <!-- Image Map Generated by http://www.image-map.net/ -->
        <client-only>
            <fullscreen ref="fullscreen">
                <orientation-alert-component/>
                <div class="overflow-auto map-images">
                    <img src="~/assets/img/map/STAND_FIJO.png" usemap="#image-map-detail">

                    <a href="#" @click="showAlert">
                        <img src="~/assets/img/elements/clickme_test.gif" alt="">
                    </a>


                    <map name="image-map-detail" id="image-map-detail">
                        <area alt="O1" title="O1" href="#" coords="116,557,43" shape="circle" @click="showAlert">
                        <area alt="O2" title="O2" href="#" coords="333,481,40" shape="circle" v-b-modal.modal>
                        <area alt="O3" title="O3" href="https://www.google.com/" coords="533,476,41" shape="circle"
                              target="_blank">
                        <area alt="O4" title="O4" href="#" coords="804,408,41" shape="circle" v-b-modal.video>
                        <area alt="O5" title="O5" href="/docs/plantilla_oral.ppt" coords="955,365,42" shape="circle" download>
                        <area alt="O6" title="O6" href="#" coords="1004,468,40" shape="circle" v-b-modal.picture>
                        <area alt="O7" title="O7" href="https://www.google.com/" coords="1135,492,40" shape="circle">
                        <area alt="O8" title="O8" href="https://www.google.com/" coords="1329,484,40" shape="circle">
                    </map>
                </div>

                <b-modal id="modal" title="Form" hide-footer>
                    <div class="form-row col">
                        <div class="form-group row">
                            <label for="">Test</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group row">
                            <label for="">Test 2</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group row">
                            <button class="btn">Enviar</button>
                        </div>
                    </div>
                </b-modal>

                <b-modal id="video" title="Video" hide-footer>
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/zpOULjyy-n8?rel=0"
                                allowfullscreen></iframe>
                    </div>
                </b-modal>

                <b-modal id="picture" title="Zoom" hide-footer>
                    <p>You can zoom the image</p>
                    <v-zoomer style="width: 100%;">
                        <img src="~/assets/images/banner.jpg" class="img-fluid">
                    </v-zoomer>
                </b-modal>
            </fullscreen>
        </client-only>

        <button @click="fullscreenChange" class="btn">Mostrar en pantalla completa</button>


    </div>
</template>

<script>
  export default {
    name: "map-one",

    methods: {
      showAlert() {
        this.$swal('Alerta', 'Mostrando alerta', 'success')
      },

      fullscreenChange() {
        this.$refs['fullscreen'].toggle();
      }
    }
  }
</script>

<style lang="scss" scoped>
    .map-images {
        position: relative;

        a {
            position: absolute;
            left: 95px;
            top: 536px;
            z-index: 9;
            width: 40px;
            height: 40px;

            img {
                width: 50px;
            }
        }
    }

</style>